blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import index, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(),
         name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('mail_app.urls', namespace='mail_app')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок',
                             unique=True, db_index=True)
    content = models.TextField(verbose_name='Содержимое статьи',
                               blank=True, null=True)
    image = models.ImageField(verbose_name='Изображение',
                              upload_to='blog/images/', blank=True,
                              null=True)
    count_views = models.IntegerField(verbose_name='Количество просмотров',
                                      default=0)
    created_at = models.DateTimeField(verbose_name='Дата публикации',
                                      auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья блога'
        verbose_name_plural = 'Статьи блога'

blog/views.py
import random

from django.shortcuts import render
from django.views.generic import DetailView

from blog.models import Blog
from blog.services import get_from_cache


def index(request):
    """ Главная страница сайта. """
    content_cache = get_from_cache()
    newsletters = content_cache[0]
    newsletters_active = content_cache[1]
    clients = content_cache[2]
    blogs = content_cache[3]
    if blogs:
        blog_list = []
        while True:
            random_blog = random.choice(blogs)
            if random_blog not in blog_list:
                blog_list.append(random_blog)
                if len(blog_list) == 3:
                    break
        blogs = blog_list
    count_newsletters = len(newsletters)
    count_newsletters_active = len(newsletters_active)
    count_clients = len(clients)

    context = {'count_newsletters': count_newsletters,
               'count_newsletters_active': count_newsletters_active,
               'count_clients': count_clients,
               'blogs': blogs}
    return render(request, 'blog/index.html', context)


class BlogDetailView(DetailView):
    """ Выводит подробную информацию о блоге. """
    model = Blog

    def get_object(self, queryset=None):
        """ Добавляет информацию о просмотрах блога. """
        obj = super().get_object(queryset)
        obj.count_views += 1
        obj.save()
        return obj

blog/templates/blog/blog_detail.html
{% extends 'mail_app/base.html' %}

{% block title %}Подробно о сообщении{% endblock %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow p-2" style="min-height: 90%; width: 90%;">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {{ blog.title }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ blog.content }}</p>
                    {% if blog.image %}
                        <a href="{{ blog.image.url }}">
                            <img src="{{ blog.image.url }}" class="m-4"
                             style="max-height: 400px; min-height: 400px;">
                        </a>
                    {% else %}
                        <img src="/media/not_image.png" class="m-4"
                             style="max-height: 400px; min-height: 400px;">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'mail_app/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-12 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-80 text-success">Общее количество рассылок</td>
                            <td class="text-warning">{{ count_newsletters }}</td>
                        </tr>
                        <tr>
                            <td class="w-80 text-success">Количество активных рассылок</td>
                            <td class="text-warning">{{ count_newsletters_active }}</td>
                        </tr>
                        <tr>
                            <td class="w-80 text-success">Количество уникальных клиентов для рассылок</td>
                            <td class="text-warning">{{ count_clients }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for blog in blogs %}
        <div class="col">
          <div class="card shadow-sm" style="min-height: 400px; max-height:
          400px;">
            {% if blog.image %}
            <img src="{{ blog.image.url }}" alt="" style="max-height:
            250px; min-height: 250px;">
            {% else %}
            <img src="/media/not_image.png" alt="" style="max-height: 250px;
            min-height: 250px;">
            {% endif %}
            <div class="card-body">
              <p class="card-text m-4">{{ blog.title | truncatechars:20 }}</p>
              <div class="d-flex justify-content-between align-items-center row text-center">
                <div class="btn-group">
                  <a type="button" href="{% url 'blog:blog_detail' blog.pk %}"
                          class="btn btn-outline-success btn-sm">Подробнее</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
</div>

{% endblock %}