blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import index, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(),
         name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('mail_app.urls', namespace='mail_app')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.utils import email_verification
from users.views import UserCreate, notification, ProfileView, UserListView, \
    UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserCreate.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification,
         name='email-confirm'),
    path('notification/', notification, name='notification'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_block'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='E-mail')
    photo = models.ImageField(verbose_name='Фото', upload_to='users/',
                              blank=True, null=True)
    phone = PhoneNumberField(region='RU', verbose_name='Телефон', blank=True,
                             null=True)
    token = models.CharField(max_length=100, verbose_name='Token', blank=True,
                             null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import BooleanField
from django import forms


class StyleFormMixin:
    """ Миксин для формы стилей. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'password1', 'password2']


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name', 'photo', 'phone']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm


def notification(request):
    return render(request, 'users/notification.html')


class UserCreate(CreateView):
    model = get_user_model()
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:notification')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(subject='Подтверждение почты',
                  message=f'Пожалуйста, подтвердите вашу почту. '
                          f'Перейдите по ссылке: {url}',
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[user.email])
        return super().form_valid(form)


class ProfileView(UpdateView):
    """ Отображает и редактирует профиль пользователя. """
    model = get_user_model()
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(PermissionRequiredMixin, ListView):
    """ Отображает список пользователей. """
    model = get_user_model()
    paginate_by = 20
    permission_required = 'mail_app.view_user'


class UserDetailView(PermissionRequiredMixin, DetailView):
    """ Отображает детальную информацию о пользователе. """
    model = get_user_model()
    permission_required = 'mail_app.view_user'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.is_active = not obj.is_active
        obj.save()
        return obj

users/templates/users/login.html
{% extends 'mail_app/base.html' %}
{% block content %}

<div class="col-12 h-100 mb-4
   d-flex align-items-center justify-content-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Авторизация</h4>
    </div>
  <div class="card-body">
     <form action="" method="post" enctype="multipart/form-data"
           class="form-floating">
      {% csrf_token %}
      {{ form.as_p }}
       <button type="submit"
               class="btn btn-lg btn-block btn-outline-success
            col-12 h-100 mb-2
            d-flex align-items-center justify-content-center">Войти
       </button>
       <p>
         <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
       </p>
     </form>
  </div>
  </div>
</div>

{% endblock %}

users/templates/users/notification.html
{% extends 'mail_app/base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row text-center">
        <div class="col-12">

                <h3>Вам отправлено письмо с подтверждением регистрации!</h3>

        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mail_app/base.html' %}
{% block content %}

<h2 class="text-warning">Пароль успешно изменен!</h2>
<p>
  Для входа в систему перейдите по ссылке
  <a href="{% url 'users:login' %}"> Вход в систему</a>
</p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mail_app/base.html' %}
{% block content %}

<div class="col-12 h-100 mb-4
   d-flex align-items-center justify-content-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Новый пароль</h4>
    </div>
  <div class="card-body">
     <form action="" method="post"
           class="form-floating">
      {% csrf_token %}
      {{ form.as_p }}
       <button type="submit"
               class="btn btn-lg btn-block btn-outline-success
            col-12 h-100 mb-2
            d-flex align-items-center justify-content-center">Сохранить
       </button>
     </form>
  </div>
  </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mail_app/base.html' %}
{% load i18n %}

{% block content %}

<h2 class="text-info">Сброс пароля</h2>

<p class="text-warning">{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p class="text-warning">{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'mail_app/base.html' %}
{% block content %}

<div class="col-12 h-100 mb-4
   d-flex align-items-center justify-content-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
    </div>
  <div class="card-body">
     <form action="" method="post"
           class="form-floating">
      {% csrf_token %}
      {{ form.as_p }}
       <button type="submit"
               class="btn btn-lg btn-block btn-outline-danger
            col-12 h-100 mb-2
            d-flex align-items-center justify-content-center">Сбросить по E-mail
       </button>
     </form>
  </div>
  </div>
</div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'mail_app/base.html' %}
{% block content %}

<br>
<div class="col-12 h-100 mb-4
   d-flex align-items-center justify-content-center">
  <div class="card mb-4 box-shadow" style="top: -30%;">
    <div class="card-header">
      {% if object.is_active %}
      <h4 class="my-4 font-weight-normal text-center text-success">Пользователь "{{ object.email }}" разблокирован! </h4>
      {% else %}
      <h4 class="my-4 font-weight-normal text-center text-danger">Пользователь "{{ object.email }}" заблокирован! </h4>
      {% endif %}
    </div>
  <div class="card-body">
     <a href="{% url 'users:users_list' %}" class="btn btn-success">&#8592; Вернуться</a>
  </div>
  </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mail_app/base.html' %}
{% block content %}

<div class="col-12 h-100 mb-4
   d-flex align-items-center justify-content-center">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      {% if user.is_authenticated %}
      <h4 class="my-0 font-weight-normal">Редактировать пользователя</h4>
      {% else %}
      <h4 class="my-0 font-weight-normal">Добавить пользователя</h4>
      {% endif %}
    </div>
  <div class="card-body">
     <form action="" method="post" enctype="multipart/form-data"
           class="form-floating">
      {% csrf_token %}
      {{ form.as_p }}
       <button type="submit"
               class="btn btn-lg btn-block btn-outline-success
            col-12 h-100 mb-2
            d-flex align-items-center justify-content-center">Сохранить
       </button>
     </form>
  </div>
  </div>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'mail_app/base.html' %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
<div class="table-responsive-xxl">
  <table class="table table-bordered border-primary border border-4 table-hover">
    <thead>
      <tr class="table-info">
      <th></th>
      <th scope="col">Статус</th>
      <th scope="col">Фото</th>
      <th scope="col">E-mail</th>
      <th scope="col">Телефон</th>
      <th scope="col">Последний вход</th>
    </tr>
    </thead>
    {% for user_ in object_list %}
    <tbody class="table-group-divider">
      <tr>
        <td>
          {% if not user_.is_superuser %}
          {% if user_.is_active %}
          <a href="{% url 'users:user_block' user_.pk%}" class="btn btn-danger">Заблокировать</a>
          {% else %}
          <a href="{% url 'users:user_block' user_.pk%}" class="btn btn-success">Разблокировать</a>
          {% endif %}
          {% else %}
          <h6 class="text-warning">Администратор</h6>
          {% endif %}
        </td>
        <td>
          <p>
          {% if user_.is_active %}
          Активный
          {% else %}
          Заблокирован
          {% endif %}
          </p>
        </td>
        <td>
          {% if user_.photo %}
          <a href="{{ user_.photo.url }}">
            <img src="{{ user_.photo.url }}" alt="" width="60" height="60">
          </a>
        {% else %}
        <img src="/media/ava.jpeg" alt="" width="60" height="60">
        {% endif %}
        </td>
        <td><p>{{ user_.email }}</p></td>
        <td><p>{{ user_.phone }}</p></td>
        <td><p>{{ user_.date_joined }}</p></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% include 'mail_app/includes/inc_paginator.html' %}
{% endblock %}