blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import index, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(),
         name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('mail_app.urls', namespace='mail_app')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mail_app/urls.py
from django.urls import path

from mail_app.views import MessageListView, ClientListView, NewsletterListView, \
    MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, NewsletterDetailView, NewsletterCreateView, \
    NewsletterUpdateView, NewsletterDeleteView, NewsletterOnOff
from .apps import MailAppConfig

app_name = MailAppConfig.name

urlpatterns = [
    path('newsletter_list/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/add/', NewsletterCreateView.as_view(),
         name='newsletter_add'),
    path('newsletters/<slug:slug>/', NewsletterDetailView.as_view(),
         name='newsletter_detail'),
    path('newsletters/<slug:slug>/edit/', NewsletterUpdateView.as_view(),
         name='newsletter_edit'),
    path('newsletters/<slug:slug>/delete/', NewsletterDeleteView.as_view(),
         name='newsletter_delete'),
    path('newsletters/on_off/<slug:slug>/', NewsletterOnOff.as_view(),
         name='newsletter_on_off'),
    path('messages/', MessageListView.as_view(), name='messages_list'),
    path('messages/add/', MessageCreateView.as_view(), name='message_add'),
    path('messages/<int:pk>/', MessageDetailView.as_view(),
         name='message_detail'),
    path('messages/<int:pk>/edit/', MessageUpdateView.as_view(),
         name='message_edit'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(),
         name='message_delete'),
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('clients/add/', ClientCreateView.as_view(), name='client_add'),
    path('clients/<slug:slug>/', ClientDetailView.as_view(),
         name='client_detail'),
    path('clients/<slug:slug>/edit/', ClientUpdateView.as_view(),
         name='client_edit'),
    path('clients/<slug:slug>/delete/', ClientDeleteView.as_view(),
         name='client_delete')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.utils import email_verification
from users.views import UserCreate, notification, ProfileView, UserListView, \
    UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserCreate.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification,
         name='email-confirm'),
    path('notification/', notification, name='notification'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_block'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='E-mail')
    photo = models.ImageField(verbose_name='Фото', upload_to='users/',
                              blank=True, null=True)
    phone = PhoneNumberField(region='RU', verbose_name='Телефон', blank=True,
                             null=True)
    token = models.CharField(max_length=100, verbose_name='Token', blank=True,
                             null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

mail_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView
from pytils.translit import slugify

from mail_app.models import Message, Client, Newsletter, MailingAttempt


class NewsletterListView(LoginRequiredMixin, ListView):
    """ Выводит общую информацию о рассылках. """
    model = Newsletter
    paginate_by = 20

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Newsletter.objects.all()
        return Newsletter.objects.filter(owner=user)


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    """ Выводит подробную информацию о рассылке. """
    model = Newsletter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clients = Client.objects.filter(newsletter=self.object)
        attempts = MailingAttempt.objects.filter(newsletter=self.object)
        context['clients'] = clients
        context['attempts'] = attempts
        return context


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    """ Создает новую рассылку. """
    model = Newsletter
    fields = ['title', 'first_sent_at', 'last_sent_at', 'status',
              'periodicity', 'message', 'clients']
    success_url = reverse_lazy('mail_app:newsletter_list')

    def form_valid(self, form):
        new_newsletter = form.save(commit=False)
        new_newsletter.slug = slugify(new_newsletter.title)
        user = self.request.user
        new_newsletter.owner = user
        new_newsletter.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        client_list = []
        new_client_list = []
        clients = Client.objects.filter(owner=user)
        for client in clients:
            client_list.append(client)
        for el in context['form'].fields['clients'].choices:
            if el[0].instance in client_list:
                new_client_list.append(el)
        context['form'].fields['clients'].choices = new_client_list
        return context


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирует рассылку. """
    model = Newsletter
    fields = ['title', 'first_sent_at', 'last_sent_at', 'status',
              'periodicity', 'message', 'clients']
    success_url = reverse_lazy('mail_app:newsletter_list')

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        client_list = []
        new_client_list = []
        clients = Client.objects.filter(owner=user)
        for client in clients:
            client_list.append(client)
        for el in context['form'].fields['clients'].choices:
            if el[0].instance in client_list:
                new_client_list.append(el)
        context['form'].fields['clients'].choices = new_client_list
        return context


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляет рассылку. """
    model = Newsletter
    success_url = reverse_lazy('mail_app:newsletter_list')


class NewsletterOnOff(PermissionRequiredMixin, DetailView):
    model = Newsletter
    template_name = 'mail_app/newsletter_on_off.html'
    permission_required = 'mail_app.off_newsletter'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.status in ['Остановлена', 'Создана']:
            obj.status = 'Запущена'
        else:
            obj.status = 'Остановлена'
        obj.save()
        return obj


class MessageListView(LoginRequiredMixin, ListView):
    """ Выводит общую информацию о сообщениях. """
    model = Message
    paginate_by = 6

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Message.objects.all()
        return Message.objects.filter(owner=user)


class MessageDetailView(DetailView):
    """ Выводит подробную информацию о сообщении. """
    model = Message

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if not self.request.user.is_authenticated:
            obj.views_count += 1
        obj.save()
        return obj


class MessageCreateView(LoginRequiredMixin, CreateView):
    """ Создает новое сообщение. """
    model = Message
    fields = ['theme', 'body', 'image']
    success_url = reverse_lazy('mail_app:messages_list')

    def form_valid(self, form):
        message = form.save(commit=False)
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирует сообщение. """
    model = Message
    fields = ['theme', 'body', 'image']
    success_url = reverse_lazy('mail_app:messages_list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляет сообщение. """
    model = Message
    success_url = reverse_lazy('mail_app:messages_list')


class ClientListView(LoginRequiredMixin, ListView):
    """ Выводит общую информацию о клиентах. """
    model = Client
    paginate_by = 20

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Client.objects.all()
        return Client.objects.filter(owner=user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """ Выводит подробную информацию о клиенте. """
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """ Создает нового клиента. """
    model = Client
    fields = ['photo', 'email', 'name', 'surname', 'father_name', 'comment',
              'status']
    success_url = reverse_lazy('mail_app:clients_list')

    def form_valid(self, form):
        new_client = form.save(commit=False)
        new_client.slug = slugify(new_client.email)
        user = self.request.user
        new_client.owner = user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирует клиента. """
    model = Client
    fields = ['photo', 'email', 'name', 'surname', 'father_name', 'comment',
              'status']
    success_url = reverse_lazy('mail_app:clients_list')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляет клиента. """
    model = Client
    success_url = reverse_lazy('mail_app:clients_list')

mail_app/templates/mail_app/includes/inc_menu.html
<div class="flex-column flex-shrink-0 p-3 bg-body-tertiary"
     style="width: 320px;">
    <a href="/"
       class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi pe-none me-2" width="40" height="32"><use
              xlink:href="#bootstrap"/></svg>
      <span class="fs-4">Навигация</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li>
        <a href="{% url 'blog:index' %}" class="nav-link link-body-emphasis" aria-current="page">
          Главная страница
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'mail_app:newsletter_list' %}"
           class="nav-link link-body-emphasis"
           aria-current="page">
          Мои рассылки
        </a>
      </li>
      <li>
        <a href="{% url 'mail_app:clients_list' %}"
           class="nav-link link-body-emphasis"
           aria-current="page">
          Клиенты
        </a>
      </li>
      <li>
        <a href="{% url 'mail_app:messages_list' %}"
           class="nav-link link-body-emphasis" aria-current="page">
          Шаблоны сообщений
        </a>
      </li>
    </ul>
    <hr>

    <div class="dropdown">
      {% if user.is_authenticated %}
      <a href="#"
         class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
         data-bs-toggle="dropdown" aria-expanded="false">
        {% if user.photo %}
        <img src="{{ user.photo.url }}" alt="" width="32" height="32"
             class="rounded-circle me-2">
        {% else %}
        <img src="/media/ava.jpeg" alt="" width="32" height="32"
             class="rounded-circle me-2">
        {% endif %}
        <strong>{{ user.email }}</strong>
      </a>
      <ul class="dropdown-menu text-small shadow">
        <li><a class="dropdown-item text-warning"
               href="{% url 'users:profile' %}">Редактировать</a></li>
        <li><a class="dropdown-item text-danger"
               href="{% url 'users:logout' %}">Выйти</a></li>
      </ul>
      {% else %}
      <a href="#"
         class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
         data-bs-toggle="dropdown" aria-expanded="false">
        <img src="/media/ava.jpeg" alt="" width="32" height="32"
             class="rounded-circle me-2">
        <strong>Профиль</strong>
      </a>
      <ul class="dropdown-menu text-small shadow">
        <li><a class="dropdown-item text-warning"
               href="{% url 'users:login' %}">Войти</a></li>
        <li><a class="dropdown-item text-info"
               href="{% url 'users:register' %}">Зарегистрироваться</a></li>
      </ul>
      {% endif %}
    </div>
    <br>
    {% if perms.mail_app.view_user %}
      <a class="dropdown-item text-warning"
         href="{% url 'users:users_list' %}">Список пользователей</a>
    {% endif %}

</div>

mail_app/templates/mail_app/includes/inc_paginator.html
<div class="col-12 h-100 d-flex align-items-center justify-content-center">
  <nav aria-label="Page navigation example" class="m-3">
    <ul class="pagination">
      {% if page_obj.has_other_pages %}

      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
      </li>
      {% endif %}

      {% for page in page_obj.paginator.page_range %}
      {% if page_obj.number == page %}
      <li class="page-item m-2"><h5>{{ page }}</h5></li>
      {% elif page >= page_obj.number|add:-3 and page <= page_obj.number|add:3 %}
      <li class="page-item"><a class="page-link" href="?page={{ page }}">
        {{ page }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
      </li>
      {% endif %}

      {% endif %}
    </ul>
  </nav>
</div>