blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import index, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(),
         name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('mail_app.urls', namespace='mail_app')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mail_app/urls.py
from django.urls import path

from mail_app.views import MessageListView, ClientListView, NewsletterListView, \
    MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, NewsletterDetailView, NewsletterCreateView, \
    NewsletterUpdateView, NewsletterDeleteView, NewsletterOnOff
from .apps import MailAppConfig

app_name = MailAppConfig.name

urlpatterns = [
    path('newsletter_list/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/add/', NewsletterCreateView.as_view(),
         name='newsletter_add'),
    path('newsletters/<slug:slug>/', NewsletterDetailView.as_view(),
         name='newsletter_detail'),
    path('newsletters/<slug:slug>/edit/', NewsletterUpdateView.as_view(),
         name='newsletter_edit'),
    path('newsletters/<slug:slug>/delete/', NewsletterDeleteView.as_view(),
         name='newsletter_delete'),
    path('newsletters/on_off/<slug:slug>/', NewsletterOnOff.as_view(),
         name='newsletter_on_off'),
    path('messages/', MessageListView.as_view(), name='messages_list'),
    path('messages/add/', MessageCreateView.as_view(), name='message_add'),
    path('messages/<int:pk>/', MessageDetailView.as_view(),
         name='message_detail'),
    path('messages/<int:pk>/edit/', MessageUpdateView.as_view(),
         name='message_edit'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(),
         name='message_delete'),
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('clients/add/', ClientCreateView.as_view(), name='client_add'),
    path('clients/<slug:slug>/', ClientDetailView.as_view(),
         name='client_detail'),
    path('clients/<slug:slug>/edit/', ClientUpdateView.as_view(),
         name='client_edit'),
    path('clients/<slug:slug>/delete/', ClientDeleteView.as_view(),
         name='client_delete')
]

mail_app/models.py
from django.db import models
from django.utils import timezone

from users.models import User

optional = {'blank': True, 'null': True}


class Client(models.Model):
    status_list = [('Активный', 'Активный'), ('Неактивный', 'Неактивный'),
                   ('Новый', 'Новый'), ('Потенциальный', 'Потенциальный'),
                   ('Заблокированный', 'Заблокированный'),
                   ('Неизвестный', 'Неизвестный')]
    photo = models.ImageField(upload_to='mail_app/clients/',
                              verbose_name='Фото', **optional)
    email = models.EmailField(unique=True, verbose_name='Email', db_index=True)
    slug = models.SlugField(max_length=255, verbose_name='Слаг', unique=True)
    name = models.CharField(max_length=255, verbose_name='Имя', **optional)
    surname = models.CharField(max_length=255, verbose_name='Фамилия',
                               **optional)
    father_name = models.CharField(max_length=255, verbose_name='Отчество',
                                   **optional)
    comment = models.TextField(verbose_name='Комментарий', **optional)
    status = models.CharField(max_length=255, choices=status_list,
                              default='Неизвестный')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата '
                                                                      'добавления')
    last_link_click = models.DateTimeField(
        verbose_name='Последний переход по ссылке', **optional)
    owner = models.ForeignKey(User, blank=True, null=True,
                              verbose_name='Владелец',
                              on_delete=models.SET_NULL,
                              related_name='client')

    def __str__(self):
        return f'{self.surname} {self.name} {self.father_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['-created_at']


class Newsletter(models.Model):
    status_list = [('Создана', 'Создана'),
                   ('Запущена', 'Запущена'),
                   ('Остановлена', 'Остановлена')]

    periodicity_list = [('День', 'День'), ('Неделя', 'Неделя'),
                        ('Месяц', 'Месяц'), ('Год', 'Год')]

    title = models.CharField(max_length=255, verbose_name='Название рассылки',
                             unique=True)
    slug = models.SlugField(max_length=255, verbose_name='Слаг', unique=True)
    first_sent_at = models.DateField(
        verbose_name='Дата первого отправления', default=timezone.now)
    last_sent_at = models.DateField(
        verbose_name='Дата крайнего отправления', default=timezone.now)
    status = models.CharField(max_length=255, choices=status_list,
                              default='Создана', verbose_name='Статус')
    periodicity = models.CharField(max_length=255,
                                   verbose_name='Периодичность',
                                   choices=periodicity_list, default='Год')
    count_sent = models.IntegerField(verbose_name='Количество отправленных',
                                     default=0)
    count_delivered = models.IntegerField(
        verbose_name='Количество доставленных', default=0)
    clients = models.ManyToManyField('Client',
                                     verbose_name='Клиенты',
                                     related_name='newsletter')
    message = models.ForeignKey('Message', on_delete=models.SET_NULL,
                                related_name='newsletter',
                                verbose_name='Сообщение', **optional)
    owner = models.ForeignKey(User, blank=True, null=True,
                              verbose_name='Владелец',
                              on_delete=models.SET_NULL,
                              related_name='newsletter')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['title']
        permissions = [
            ('view_user', 'Просматривать список пользователей сервиса'),
            ('block_user', 'Блокировать пользователей сервиса'),
            ('off_newsletter', 'Отключать рассылки')
        ]


class Message(models.Model):
    theme = models.CharField(max_length=255, verbose_name='Тема сообщения',
                             **optional)
    body = models.TextField(verbose_name='Текст сообщения', **optional)
    image = models.ImageField(upload_to='mail_app/messages/',
                              verbose_name='Изображение', **optional)
    views_count = models.PositiveIntegerField(
        verbose_name='Количество переходов', default=0)
    owner = models.ForeignKey(User, blank=True, null=True,
                              verbose_name='Владелец',
                              on_delete=models.SET_NULL,
                              related_name='message')

    def __str__(self):
        return self.theme

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['id']


class MailingAttempt(models.Model):
    last_attempt_at = models.DateTimeField(auto_now=True,
                                           verbose_name='Последняя попытка '
                                                        'отправки')
    successfully = models.BooleanField(default=False, verbose_name='Успешно?')
    mail_response = models.CharField(max_length=255,
                                     verbose_name='Ответ сервера', **optional)
    newsletter = models.ForeignKey('Newsletter', on_delete=models.CASCADE,
                                   verbose_name='Рассылка',
                                   related_name='attempt')

    def __str__(self):
        return f'{self.last_attempt_at} {self.successfully} {self.mail_response}'

    class Meta:
        verbose_name = 'Попытка отправки рассылки'
        verbose_name_plural = 'Попытки отправки рассылок'
        ordering = ['-last_attempt_at']

mail_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView
from pytils.translit import slugify

from mail_app.models import Message, Client, Newsletter, MailingAttempt


class NewsletterListView(LoginRequiredMixin, ListView):
    """ Выводит общую информацию о рассылках. """
    model = Newsletter
    paginate_by = 20

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Newsletter.objects.all()
        return Newsletter.objects.filter(owner=user)


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    """ Выводит подробную информацию о рассылке. """
    model = Newsletter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clients = Client.objects.filter(newsletter=self.object)
        attempts = MailingAttempt.objects.filter(newsletter=self.object)
        context['clients'] = clients
        context['attempts'] = attempts
        return context


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    """ Создает новую рассылку. """
    model = Newsletter
    fields = ['title', 'first_sent_at', 'last_sent_at', 'status',
              'periodicity', 'message', 'clients']
    success_url = reverse_lazy('mail_app:newsletter_list')

    def form_valid(self, form):
        new_newsletter = form.save(commit=False)
        new_newsletter.slug = slugify(new_newsletter.title)
        user = self.request.user
        new_newsletter.owner = user
        new_newsletter.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        client_list = []
        new_client_list = []
        clients = Client.objects.filter(owner=user)
        for client in clients:
            client_list.append(client)
        for el in context['form'].fields['clients'].choices:
            if el[0].instance in client_list:
                new_client_list.append(el)
        context['form'].fields['clients'].choices = new_client_list
        return context


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирует рассылку. """
    model = Newsletter
    fields = ['title', 'first_sent_at', 'last_sent_at', 'status',
              'periodicity', 'message', 'clients']
    success_url = reverse_lazy('mail_app:newsletter_list')

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        client_list = []
        new_client_list = []
        clients = Client.objects.filter(owner=user)
        for client in clients:
            client_list.append(client)
        for el in context['form'].fields['clients'].choices:
            if el[0].instance in client_list:
                new_client_list.append(el)
        context['form'].fields['clients'].choices = new_client_list
        return context


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляет рассылку. """
    model = Newsletter
    success_url = reverse_lazy('mail_app:newsletter_list')


class NewsletterOnOff(PermissionRequiredMixin, DetailView):
    model = Newsletter
    template_name = 'mail_app/newsletter_on_off.html'
    permission_required = 'mail_app.off_newsletter'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.status in ['Остановлена', 'Создана']:
            obj.status = 'Запущена'
        else:
            obj.status = 'Остановлена'
        obj.save()
        return obj


class MessageListView(LoginRequiredMixin, ListView):
    """ Выводит общую информацию о сообщениях. """
    model = Message
    paginate_by = 6

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Message.objects.all()
        return Message.objects.filter(owner=user)


class MessageDetailView(DetailView):
    """ Выводит подробную информацию о сообщении. """
    model = Message

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if not self.request.user.is_authenticated:
            obj.views_count += 1
        obj.save()
        return obj


class MessageCreateView(LoginRequiredMixin, CreateView):
    """ Создает новое сообщение. """
    model = Message
    fields = ['theme', 'body', 'image']
    success_url = reverse_lazy('mail_app:messages_list')

    def form_valid(self, form):
        message = form.save(commit=False)
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирует сообщение. """
    model = Message
    fields = ['theme', 'body', 'image']
    success_url = reverse_lazy('mail_app:messages_list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляет сообщение. """
    model = Message
    success_url = reverse_lazy('mail_app:messages_list')


class ClientListView(LoginRequiredMixin, ListView):
    """ Выводит общую информацию о клиентах. """
    model = Client
    paginate_by = 20

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Client.objects.all()
        return Client.objects.filter(owner=user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """ Выводит подробную информацию о клиенте. """
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """ Создает нового клиента. """
    model = Client
    fields = ['photo', 'email', 'name', 'surname', 'father_name', 'comment',
              'status']
    success_url = reverse_lazy('mail_app:clients_list')

    def form_valid(self, form):
        new_client = form.save(commit=False)
        new_client.slug = slugify(new_client.email)
        user = self.request.user
        new_client.owner = user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирует клиента. """
    model = Client
    fields = ['photo', 'email', 'name', 'surname', 'father_name', 'comment',
              'status']
    success_url = reverse_lazy('mail_app:clients_list')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляет клиента. """
    model = Client
    success_url = reverse_lazy('mail_app:clients_list')

mail_app/templates/mail_app/client_list.html
{% extends 'mail_app/base.html' %}

{% block title %}Список клиентов{% endblock %}

{% block content %}
<div class="table-responsive-xxl">
  <table class="table table-bordered border-primary border border-4 table-hover">
    <thead>
      <tr class="table-info">
      <th scope="col">Email</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Отчество</th>
      <th scope="col">Статус</th>
      <th scope="col">Рассылка</th>
    </tr>
    </thead>
    {% for client in object_list %}
    {% if client.status == 'Заблокированный' %}
    <tbody class="table-group-divider">
      <tr>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis text-danger">{{ client.email }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis text-danger">{{ client.name }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis text-danger">{{ client.surname }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis text-danger">{{ client.father_name }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis text-danger">{{ client.status }}</a></td>
        <td>
    {% else %}
      <tbody class="table-group-divider">
      <tr>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis">{{ client.email }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis">{{ client.name }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis">{{ client.surname }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis">{{ client.father_name }}</a></td>
        <td><a href="{% url 'mail_app:client_detail' client.slug %}" class="nav-link link-body-emphasis">{{ client.status }}</a></td>
        <td>
    {% endif %}
          <div class="btn-group">
            {% if client.newsletter.all %}
          <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Развернуть...
          </button>
          <ul class="dropdown-menu">
            {% for newsletter in client.newsletter.all %}
            <li><a class="dropdown-item" href="{% url 'mail_app:newsletter_detail' newsletter.slug %}">{{ newsletter | truncatechars:30 }}</a></li>
            {% endfor %}
            {% else %}
            <p class="p-2" style="width: 200px; height: 20px;">Нет рассылок.</p>
            {% endif %}
          </ul>
        </div>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% if user.is_authenticated %}
{% if not perms.mail_app.off_newsletter or user.is_superuser %}
<div class="col-12 m-3
   d-flex align-items-center justify-content-center">
  <a href="{% url 'mail_app:client_add' %}"
     class="btn btn-block btn-outline-success btn-lg"
     role="button">Добавить клиента
  </a>
</div>
{% endif %}
{% endif %}
{% include 'mail_app/includes/inc_paginator.html' %}
{% endblock %}

mail_app/templates/mail_app/mail_list.html
{% extends 'mail_app/base.html' %}

{% block content %}
  <table class="table table-bordered border-primary border border-4 table-hover">
    <thead>
      <tr class="table-info">
      <th scope="col">Номер</th>
      <th scope="col">Название</th>
      <th scope="col">Отправлено</th>
      <th scope="col">Доставлено</th>
      <th scope="col">Прочитано</th>
      <th scope="col">Переходов</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
      <tr>
        <th scope="row">1</th>
        <td><a href="#">Рассылка 1</a></td>
        <td>20</td>
        <td>15</td>
        <td>10</td>
        <td>200</td>
      </tr>
    </tbody>
</table>
{% endblock %}

mail_app/templates/mail_app/newsletter_detail.html
{% extends 'mail_app/base.html' %}

{% block title %}Подробно о рассылке{% endblock %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow p-2" style="min-height: 90%; width: 90%;">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        Параметры рассылки</h4>
                </div>
                <div class="card-body">
                    <div class="col">
                        <div class="row">
                            <div class="col-12">

                                <table class="table">
                                  <thead>
                                    <tr>
                                      <th class="text-lg">Основная информация</th>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Название рассылки</th>
                                      <td style="word-break: break-all;">{{ newsletter.title }}</td>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <tr>
                                      <th class="text-lg-start">Сообщение</th>
                                      <td style="word-break: break-all;">
                                        {% if newsletter.message %}
                                        <ins>
                                          <a href="{% url 'mail_app:message_detail' newsletter.message.pk %}" class="nav-link link-body-emphasis">
                                          {{ newsletter.message }}</a>
                                        </ins>
                                        {% else %}
                                        <p>-</p>
                                        {% endif %}
                                      </td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Статус</th>
                                      <td style="word-break: break-all;">{{ newsletter.status }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Дата первого отправления</th>
                                      <td style="word-break: break-all;">{{ newsletter.first_sent_at }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Дата крайнего отправления</th>
                                      <td style="word-break: break-all;">{{ newsletter.last_sent_at }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Периодичность</th>
                                      <td style="word-break: break-all;">{{ newsletter.periodicity }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Количество отправленных</th>
                                      <td style="word-break: break-all;">{{ newsletter.count_sent }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Количество доставленных</th>
                                      <td style="word-break: break-all;">{{ newsletter.count_delivered }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Количество переходов</th>
                                      <td style="word-break: break-all;">{{ newsletter.message.views_count }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg">Статистика попыток</th>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Последняя попытка отправки</th>
                                      <td style="word-break: break-all;">{{ attempts.0.last_attempt_at }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Успешность отправки</th>
                                      <td style="word-break: break-all;">{{ attempts.0.successfully }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Ответ сервера</th>
                                      <td style="word-break: break-all;">{{ attempts.0.mail_response }}</td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">
                                        <ins>

                                          <div class="btn-group">
                                          <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                            Подробнее...
                                          </button>
                                          <ul class="dropdown-menu">
                                            {% if attempts %}
                                            <p class="p-2">Последняя попытка отправки | Успешность отправки | Ответ сервера</p>
                                            {% for attempt in attempts %}
                                            <li style="width: 580px;" class="p-2">
                                              <p>
                                                {{ attempt.last_attempt_at }}.................................{{ attempt.successfully }}...............................{{ attempt.mail_response }}
                                              </p>
                                            </li>
                                            {% endfor %}
                                            {% else %}
                                            <p class="p-2" style="width: 200px; height: 20px;">Нет попыток отправки.</p>
                                            {% endif %}
                                          </ul>
                                        </div>

                                        </ins>
                                      </th>
                                      <td style="word-break: break-all;"></td>
                                    </tr>
                                    <tr>
                                      <th class="text-lg">Доп. информация</th>
                                    </tr>
                                    <tr>
                                      <th class="text-lg-start">Закрепленные клиенты</th>
                                      <td style="word-break: break-all;">

                                        <div class="btn-group">
                                          <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                            Список
                                          </button>
                                          <ul class="dropdown-menu">
                                            {% if clients %}
                                            {% for client in clients %}
                                            <li><a class="dropdown-item" href="{% url 'mail_app:client_detail' client.slug %}">{{ client | truncatechars:30 }}</a></li>
                                            {% endfor %}
                                            {% else %}
                                            <p class="p-2" style="width: 200px; height: 20px;">Нет клиентов.</p>
                                            {% endif %}
                                          </ul>
                                        </div>

                                      </td>
                                    </tr>
                                  </tbody>
                                </table>

                        </div>
                    </div>

                </div>
                {% if user.is_authenticated %}
                {% if not perms.mail_app.off_newsletter or user.is_superuser %}
                <div class="card-footer">
                    <a href="{% url 'mail_app:newsletter_edit' newsletter.slug %}"
                           class="btn btn-lg btn-block btn-outline-warning m-2"
                           role="button">
                          Редактировать
                    </a>
                    <a href="{% url 'mail_app:newsletter_delete' newsletter.slug %}"
                           class="btn btn-lg btn-block btn-outline-danger"
                           role="button">
                          Удалить
                    </a>
                </div>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mail_app/templates/mail_app/newsletter_list.html
{% extends 'mail_app/base.html' %}

{% block title %}Список рассылок{% endblock %}

{% block content %}
  <table class="table table-bordered border-primary border border-4 table-hover">
    <thead>
      <tr class="table-info">
      {% if perms.mail_app.off_newsletter %}
      <th scope="col"></th>
      {% endif %}
      <th scope="col">Название</th>
      <th scope="col">Сообщение</th>
      <th scope="col">Статус</th>
      <th scope="col">Дата первого отправления</th>
      <th scope="col">Дата крайнего отправления</th>
      <th scope="col">Периодичность</th>
    </tr>
    </thead>
    {% for newsletter in object_list %}
    <tbody class="table-group-divider">
      <tr>
        {% if perms.mail_app.off_newsletter %}
        {% if newsletter.status == 'Остановлена' or newsletter.status == 'Создана' %}
        <th><a type="button"
               class="btn btn-outline-success"
               href="{% url 'mail_app:newsletter_on_off' newsletter.slug %}">Запустить</a></th>
        {% else %}
        <th><a type="button"
               class="btn btn-outline-danger"
               href="{% url 'mail_app:newsletter_on_off' newsletter.slug %}">Остановить</a></th>
        {% endif %}
        {% endif %}
        <td><a href="{% url 'mail_app:newsletter_detail' newsletter.slug %}"
               class="nav-link link-body-emphasis">{{ newsletter.title }}</a></td>
        <td>
          {% if newsletter.message %}
          <a href="{% url 'mail_app:message_detail' newsletter.message.pk %}">{{ newsletter.message }}</a>
          {% else %}
          <p>-</p>
          {% endif %}
        </td>
        <td><a href="{% url 'mail_app:newsletter_detail' newsletter.slug %}"
               class="nav-link link-body-emphasis">{{ newsletter.status }}</a></td>
        <td><a href="{% url 'mail_app:newsletter_detail' newsletter.slug %}"
               class="nav-link link-body-emphasis">{{ newsletter.first_sent_at }}</a></td>
        <td><a href="{% url 'mail_app:newsletter_detail' newsletter.slug %}"
               class="nav-link link-body-emphasis">{{ newsletter.last_sent_at }}</a></td>
        <td><a href="{% url 'mail_app:newsletter_detail' newsletter.slug %}"
               class="nav-link link-body-emphasis">{{ newsletter.periodicity }}</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>
{% if user.is_authenticated %}
{% if not perms.mail_app.off_newsletter or user.is_superuser %}
<div class="col-12 m-3
   d-flex align-items-center justify-content-center">
  <a href="{% url 'mail_app:newsletter_add' %}"
     class="btn btn-block btn-outline-success btn-lg"
     role="button">Добавить рассылку
  </a>
</div>
{% endif %}
{% endif %}
{% endblock %}